name: Get changed modules

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tenant:
        type: string
        required: true
    outputs:
      clusters:
        value: ${{ jobs.main.outputs.clusters }}
      tenantId:
        value: ${{ jobs.main.outputs.tenantId }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      clusters: ${{ steps.get-clusters.outputs.clusters }}
      tenantId: ${{ steps.get-clusters.outputs.tenantId }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get clusters
        id: get-clusters
        #env:
        #  githubToken: ${{ secrets.BICEP_GITHUBACTIONS_PAT }}
        shell: pwsh
        run: |
          $environment = '${{ inputs.environment }}'
          $tenant = '${{ inputs.tenant }}'
          $configFile = "./azure/configs/aks-$tenant-$environment.jsonc"
          $jsonc = Get-Content -Path $configFile -Raw
          $json = $jsonc -replace '(?m)(?<=^([^"]|"[^"]*")*)//.*' -replace '(?ms)/\*.*?\*/'
          $json | Out-File -FilePath ./configtemp.json -Encoding utf8
          $config = Get-Content ./configtemp.json -Raw | ConvertFrom-Json #-Depth 100

          Write-Output ('{0}={1}' -f 'clusters', (ConvertTo-Json @($config.aksClusters) -Compress))
          Write-Output ('{0}={1}' -f 'clusters', (ConvertTo-Json @($config.aksClusters) -Compress)) >> $env:GITHUB_OUTPUT
          Write-Output ('{0}={1}' -f 'tenantId', $config.tenantId)
          Write-Output ('{0}={1}' -f 'tenantId', $config.tenantId) >> $env:GITHUB_OUTPUT